version: '3.5'

services:
  symfony-structure-web:
    container_name: symfony-structure-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - symfony-structure-be
    networks:
      - symfony-structure-network

  symfony-structure-be:
    container_name: symfony-structure-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      #      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005 # MacOS users
    volumes:
      - ./:/appdata/www
#      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug-macos.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - symfony-structure-db
    networks:
      - symfony-structure-network

  symfony-structure-db:
    container_name: symfony-structure-db
    image: mysql:8.0
    build:
      context: ./docker/database
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: structure_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony-structure-db-data:/var/lib/mysql
    networks:
      - symfony-structure-network

volumes:

  symfony-structure-db-data:

networks:
  symfony-structure-network:
    external: true
